version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands : 
      - cp ./settings.xml /root/.m2/settings-security.xml
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile package install deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/Core-0.1.jar